# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bloodbankdb
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate Configuration
# update = table nahi hai toh bana do, hai toh update karo
spring.jpa.hibernate.ddl-auto=update

# Console mein SQL dikhao
spring.jpa.show-sql=true

# SQL properly formatted dikhao
spring.jpa.properties.hibernate.format_sql=true

# open-in-view warning band karo
spring.jpa.open-in-view=false

# App name
spring.application.name=bloodbank


# JWT Configuration
# Yeh secret key hai jisse token sign hoga
# Koi bhi random long string rakho
jwt.secret=bloodbank-healthcare-secret-key-2024-very-long-string
jwt.expiration=86400000

# Security debug logging
logging.level.org.springframework.security=DEBUG